name: primeira-pipeline
on:
  push:
    branches:  ["main"]
  workflow_dispatch: 
jobs:
  primeiro-job:
    name: "Meu primeiro job"
    runs-on: ubuntu-latest
    steps:
      - name: "Minha primeira acao"
        run: echo "Hello World !!!"
      - name: "Segunda acao"
        run:  |
          echo "Voce criou o seu primeiro workflow !!!"
          echo "Parabens !!!"
      - name: "Script Python"
        run:  |
          variavel = "Hello World !!!"
          print(variavel)
        shell: python
  segundo-job:
    name: "Instalacao do Ambiente NodeJS"
    runs-on: ubuntu-latest
    steps:
       - name: "verificacao da versao do NodeJS atual"
         run: node --version
          
